name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - name: build script
        run: |
          cd scripts
          ./build.sh -

      - name: upload script
        uses: actions/upload-artifact@v3
        with:
          name: linux-live
          path: |
            scripts/linux-live.iso
            scripts/md5sum.txt
